language: c
sudo: false
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libglew-dev
    - libxkbcommon-dev
    - libx11-dev
script:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - make
