language: c
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libglew-dev
    - libxkbcommon-dev
    - libx11-dev
    - libxxf86vm-dev
script:
  - make
