language: c
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libglew-dev
    - libx11-dev
    - libxxf86vm-dev
    - xutils-dev
script:
  - make
